### ISSUE TITLE
nightly.link workflow stuck/bugged, was working fine till now

### ISSUE THREAD

**Issue by brian6932** [oprypin/nightly.link#49] opened 2023-02-05 17:02 UTC
https://nightly.link/streamlink/windows-builds/workflows/nightly/master
Latest workflow run: https://github.com/streamlink/windows-builds/actions/runs/4094201396

**Comment by oprypin** [comment] 2023-02-05 17:32
* Probably duplicate of https://github.com/oprypin/nightly.link/issues/26

**Comment by oprypin** [comment] 2023-02-05 17:34
Yes, see here:
GitHub itself is serving wrong information here:
https://github.com/streamlink/windows-builds/actions?query=event%3Apush+is%3Acompleted+branch%3Amaster
nightly.link is serving from this source so it's also going to be stale

**Closed by oprypin** 2023-02-05 17:34 UTC
